// <auto-generated />
namespace TestAPIV5N1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initk));
        
        string IMigrationMetadata.Id
        {
            get { return "202401121548024_initk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
